### ISSUE TITLE
Add GUI

### ISSUE THREAD

**Issue by ll-nick** [KIT-MRT/arbitration_graphs#22]
There is this beautiful GUI to visualize the arbitration graphs. Let's add it to the repo and make is easy to work with for our enormous user base.

**Comment by orzechow** [comment]
Sth. we could also concider for the GUI communication:
- https://socket.io/docs/v4/

**Comment by orzechow** [comment]
The [libwebsockets](https://libwebsockets.org/) used in
- #10 

is C only, thus very ugly and unsafe.

Let's investigate into modern C++ websocket libraries.

I'll start with
- [uWebSockets](https://github.com/uNetworking/uWebSockets)

**Comment by orzechow** [comment]
- [restinio](https://github.com/Stiffstream/restinio) could be nice, but has a lot of dependencies

**Comment by ll-nick** [comment]
Closed with #10 :tada:
