### ISSUE TITLE
Readme image alignment

### ISSUE THREAD

**Issue by ll-nick** [KIT-MRT/arbitration_graphs#46]
I just merged https://github.com/KIT-MRT/arbitration_graphs/pull/44 but only looked at the rendered markdown locally.

On GitHub, the centering is off. I wanted the images to be vertically centered which they now are not. @orzechow do you happen to know how we can fix that?

An alternative solution would be to have the images stacked vertically which would be fine too I guess:

```
<p align="center">
  <img src="docs/pacman_scenario.png" width="400" />
</p>
<p align="center">
  <img src="docs/pacman_arbitrator_safe.svg" width="500" /> 
</p>
```
![two_lines_layout](https://github.com/user-attachments/assets/ae083461-20fc-494f-9d29-27678411bdf2)

**Comment by orzechow** [comment]
Yeah, agree 👍
