### ISSUE TITLE
Add Icon

### ISSUE THREAD

**Issue by ll-nick** [KIT-MRT/arbitration_graphs#49]
We should add an icon to the repo. How about something in the general direction of:

![decision_making_icon](https://github.com/user-attachments/assets/f08c9d9a-0141-4d3c-9bb4-9c795098d28b)

Maybe a little less wide and with rounded off arrows?

**Comment by ll-nick** [comment]
[From what I can tell](https://github.com/orgs/community/discussions/22019), the repository's icon/logo/thumbnail cannot actually be changed. If you go to https://github.com/KIT-MRT/arbitration_graphs, you will always see the mrt logo in the top left corner.
What *can* be changed is the social media preview. I.e. the thumbnail that's visible when sending a link to the readme via e.g. a messenger. I do not think that this use case is worth the effort to come up with an icon.

So either we would also utilize the icon elsewhere, i.e. at the top of the readme or we don't and simply close this issue.
@orzechow What do you think?

**Comment by orzechow** [comment]
For now, I don't see us creating an icon in the near future... 😔
