### ISSUE TITLE
Setup continuous deployments (releases + ghcr.io docker image) 

### ISSUE THREAD

**Issue by orzechow** [KIT-MRT/arbitration_graphs#59]
Let's write some GitHub Actions to automatically 
- [x] run the unit tests (on every push)
  - [x] Core library
  - [x] Demo
- [x] deploy releases (on every merge into `main`)
  - [x] bump version
  - [x] create and push git tag with new version
  - [x] deploy tar as release asset
  - [x] build & deploy docker image with latest tag to ghcr.io
    - [x] [Core library](https://github.com/kit-mrt/arbitration_graphs/pkgs/container/arbitration_graphs) 
    - [x] [Demo](https://github.com/kit-mrt/arbitration_graphs/pkgs/container/arbitration_graphs_pacman_demo)
    - [x] [Tutorial](https://github.com/kit-mrt/arbitration_graphs/pkgs/container/arbitration_graphs_pacman_tutorial)
  - [x] update `latest` tags of docker images on ghcr.io

We should make sure to also
- [x] cleanup and update the main Readme w.r.t. installation options

**Comment by orzechow** [comment]
@ll-nick FYI

**Comment by ll-nick** [comment]
And let's run the unit tests too

**Comment by ll-nick** [comment]
I just added a workflow for executing the unit tests, see #61 

To make sure it actually fails if a test fails, I pushed a broken commit (but fixed it again after :stuck_out_tongue_closed_eyes: ), see the [workflows](https://github.com/KIT-MRT/arbitration_graphs/actions/workflows/run-unit-tests.yaml).

So far, that only covers the unit tests of the core library. Testing the demo unit tests only makes sense after we merged them to main (same goes for the docker deployment which is also done for the core library already).

**Comment by ll-nick** [comment]
Oh and for the tar releases, we probably need some versioning system right? Or do we simply deploy a dev release using the main branch?

**Comment by orzechow** [comment]
> Oh and for the tar releases, we probably need some versioning system right? Or do we simply deploy a dev release using the main branch?

I'll setup a semantic versioning for that and the docker images as well.

**Comment by orzechow** [comment]
Alright, so I thought about the versioning.
Auto-bumping e.g. the patch version with each merged PR would be easy. But we'd like to be able to bump major or minor versions as well in some smart manner.

Now, there's a ton of tools to ease semantic versioning, releases etc. (most overkill).
From full blown npm beasts like [semantic-release](https://github.com/semantic-release/semantic-release) (and its [github action part](https://github.com/semantic-release/github)) to smaller (but less maintained) GitHub Actions like [github-tag](https://github.com/marketplace/actions/github-tag) and [github-tag-bump](https://github.com/marketplace/actions/github-tag-bump)

The latter is quite nice, it checks the commit log for bumping commands (`#major`, #minor`, `#patch`) with `patch` as default and tags the git commit.
This new tag is also available as action output for following actions (like updating the `version` file, deploying etc.)

**Comment by ll-nick** [comment]
That sounds good. I like the version bump on merge to main. Sounds like little overhead and I think anything more than that is probably going to be overkill for what we do here :+1:

**Comment by ll-nick** [comment]
@orzechow Do we want to release docker images for the demo on ghcr as well?

**Comment by ll-nick** [comment]
> Do we want to release docker images for the demo on ghcr as well?

Ah nevermind, I missed it in the todo list above. I'll add that to the workflow too.

**Comment by orzechow** [comment]
> @orzechow Do we want to release docker images for the demo on ghcr as well?

Why not? :grin: 

Users would still need the compose file though for X11 settings etc. (or we provide a docker run command with all these settings)

**Comment by ll-nick** [comment]
I just added that workflow to #61 

> Users would still need the compose file though for X11 settings etc. (or we provide a docker run command with all these settings)

You're right but then we are basically better of with docker compose.

We could just change the service and remove the `build:` setting. The docker deploy workflow does not rely on this service so I guess that would be easiest.

**Comment by ll-nick** [comment]
Completed with #61 :tada:

**Comment by orzechow** [comment]
@ll-nick FYI: our current approach with bumping the version after PR merge, can fail when merging multiple PRs in a short period (as I did with #91, #93, #94 and #95).
E.g. update-version-file of [job 33586229265](https://github.com/KIT-MRT/arbitration_graphs/actions/runs/12046211093/job/33586229265) failed, because main has changed between the jobs repo checkout and push.

It's a rare edge case, but doesn't feel great…

**Comment by ll-nick** [comment]
Yes, I'm aware of that. I purposefully merged stuff one at a time in the past but of course that's not the nicest solution. GitHub actually [has a setting for that](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs). We should look into that. At first glance, this seems like it would solve our problem.
