### ISSUE TITLE
Add debian package

### ISSUE THREAD

**Issue by ll-nick** [KIT-MRT/arbitration_graphs#65]
I was just thinking about how to integrate this package on MRT side. The two options I see are either a catkin wrapper or a debian package. The latter would have the additional benefit of being a relatively universal solution that would also simplify the usage of the library for other users.

I vaguely remember we discussed this a while ago and that creating debian packages isn't exactly the most straightforward process. Still, it would be nice to integrate it into the versioning/ci system that #59 would already add to the library.

Are there any reasons not to do that? Is the overhead very large? Maybe you can add your experiences @orzechow

**Comment by orzechow** [comment]
Well, AFAIR using the official debian packaging stuff (dh_make, debhelper and such) was bit of a pain.
It's designed to solve most setups in a "auto-magical" fashion, but to support any kind of exotic packaging construct as well – that IMHO explains the elaborate [Debian New Maintainers' Guide](https://www.debian.org/doc/manuals/maint-guide/index.en.html).

As we're dealing with a rather simple C++/CMake library here, I guess the dh_make stuff is overkill.
CPack seems to provide a [rather easier approach](https://cliutils.gitlab.io/modern-cmake/chapters/install/packaging.html) for CMake projects, though I have no experience with it yet.
See also [ChatGPTs CPack suggestions](https://chatgpt.com/share/6728ad75-aaa0-8010-8e7d-f8b0c738966e).

CPack can generate `.deb` packages and `.tar.gz`/`.zip` source archives.

**Comment by orzechow** [comment]
CPAck is awesome!

See a working draft: #70

**Comment by ll-nick** [comment]
Completed with #70 :100:
