### ISSUE TITLE
GitHub version bump action always bumps at least minor

### ISSUE THREAD

**Issue by orzechow** [KIT-MRT/arbitration_graphs#79]
Our GitHub version bump action has this version bump combination logic based on commit messages (see also https://github.com/KIT-MRT/util_caching/issues/38#issuecomment-2476138840).
It seems that in our setup with a PR merge commit, this leads to version bumping based on
- the PR commits 
- plus the PR merge commit

In #75, this lead to a minor bump, even though the only PR commit 3586225 contains the `#patch` tag.
That's probably, because the PR merge commit does not contain a bump tag – thus, defaulting to `#minor`

It's a pity we have so much trouble with the version bump action :see_no_evil: 

@ll-nick Any idea how we can fix this? Should we default to `#patch` again?

**Comment by orzechow** [comment]
Kinda okayish inspiration for a custom implementation:
https://chatgpt.com/share/673c56c9-d468-8010-a15c-0bc2db517f69

**Comment by orzechow** [comment]
Well that worked "well" :sweat_smile: 

![image](https://github.com/user-attachments/assets/51255cdb-9be2-4614-93cd-ed34fca2ecfd)

**Comment by ll-nick** [comment]
See https://github.com/KIT-MRT/arbitration_graphs/pull/87

**Comment by ll-nick** [comment]
The reason for the major release is a stupid one. The PR description contained
> of one of the following flags (proceeded by a #):
 >  - major
 
 After sanitizing that you get
 > ofoneofthefollowingflagsproceededbya#major
 which contains #major which caused a major release.
 
 Merging #87 fixes the version and I think we can close this issue again after. That's a stupid coincidence that I doubt will happen again.

**Comment by orzechow** [comment]
And I wondered, if you might want to preserve whitespaces as well – would that be unsafe?

**Comment by ll-nick** [comment]
I guess we could adjust the sanitizing to keep whitespaces too just to make it less likely of this happening again :+1:
